######################################
#
# a script to pull the data from the downloaded csv. The data comes from the UN
# sustainable development goals indicators database. 
# https://unstats.un.org/sdgs/indicators/database/
# read this article to learn how to pull API data:
# https://www.dataquest.io/blog/r-api-tutorial/
#
######################################

#install.packages('httr')
#install.packages('jsonlite')

library(httr)
library(jsonlite)

response <- GET('https://unstats.un.org/SDGAPI/v1/sdg/Indicator/Data?indicator=5.4.1')
#send a get request to the UNSDGI API server using httr. print response
#to see if a valid request was made (200 status). The url above was generated by the UN site

data <- fromJSON(rawToChar(response$content))
#the stuff we want is in the content part of response. First need to convert it to a 
#raw char string, then parse it using the fromJSON function

names(data) #print the things within data. We are looking for a specific column
#where the data we want lives. In this case it's called data

str(data$data)
#confirm this is what we are looking for

unpaid_stats_df <- data$data
temp <- tidyr::unnest(unpaid_stats_df, cols = c('goal', 'target', 'indicator', 'footnotes',
                                                'attributes', 'dimensions'))
#need to flatten the data so each row has the correct attributes and dimensions associated with it.
#attributes and dimensions are both columns of data frames, i.e., each item in attribute and dimensions is
#its own data frame

unpaid_stats_df_subset <- unpaid_stats_df[ , c('goal', 'target', 'indicator', 'seriesDescription',
                                               'seriesCount', 'geoAreaCode', 'geoAreaName', 'timePeriodStart',
                                               'value','source', 'attributes', 'dimensions')]


write.csv(unpaid_stats_df, 'data/un-unpaid-labor-data.csv', row.names = FALSE)
#export as a csv
